services:
  # Backend API (Node.js + Express)
  - type: web
    name: gymsage-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ANALYZER_URL
        sync: false
    healthCheckPath: /api/health

  # Python Analyzer Service (FastAPI)
  - type: web
    name: gymsage-analyzer
    runtime: python
    region: oregon
    plan: free
    buildCommand: cd analyzer && pip install -r requirements.txt
    startCommand: cd analyzer && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /health
